### ISSUE TITLE
How to create models in golang?

### ISSUE THREAD

**Issue by arnwas** [galeone/tfgo#23]
Is there a feasible way to create and train new models within golang? Either by tfgo, or other tools?

**Comment by galeone** [comment]
Right now is not possible, because the Go API is only able to define some simple graph, but there is not a Go equivalent of the `tf.Variable` Python class.

If you want to define a model and train it in Go, you have to use Python to define the computational graph of the whole training loop, then export this training loop graph, load it in Go and execute it (in the same way of executing the inference).

I've started a project, btw, that will expose the whole TensorFlow Python API to Go. I haven't had the time to go on with the development (I will soon) - you can read more here: https://github.com/galeone/tfgo/issues/17#issuecomment-480625922

If you want to contribute to this project, just le me know it

**Comment by galeone** [comment]
Hi @Arnold1 , you can use the [`model.LoadModel(exportDir string, tags []string, options *tf.SessionOptions) (model *Model)`](https://github.com/galeone/tfgo/blob/06635831fc69e3c9f0ca52e2a5606f07987ad13c/model.go#L31)

Where:

- `export_dir` is the path that contains your `saved_model.pb` 
- `tags` is the array of tags (usually something lie `{"serve"}` but the tag name depends on youw you tagged the model during the export (in Python)
- `options` usually are just `nil`

You can see an example here: https://github.com/galeone/tfgo#go-code

**Comment by Arnold1** [comment]
@galeone thanks so much.

also was is the difference to tensor flow serving and this lib?

**Comment by galeone** [comment]
No wait wait. I linked you an example, you don't need my `test_models/export` folder, you can use your model.

The tag "tag" is the tag I used when exporting the savedmodel. You already showed that you used the tag "serve" (you're inspecting the saved model structure at the "serve" tag using saved_model_cli), so instead of  `{"tag"}` you have to use `{"serve"}` (and you did this correctly).

Now, instead of  `input_:0" (that's the name of the input placeholder I used in the example), you have to use one (or all) the input placeholder you have in your model, like Placeholder_1:0, Placeholder_2:0  and so on.

You have also to specify the output you want (instead of my LenetDropput/etc..., you have to use one of the output tensor defined in your saved model, like `prob_out:0`).

Also, this library is able to do pretty much the same things of TensorFlow serving (you can create an equivalent of TensorFlow serving in Go using the library), but it gives you more flexibility since you can use all the Go bindings

**Comment by Arnold1** [comment]
@galeone 

I tried the following but see:
```
2020-01-31 08:29:34.379920: I tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: model/123123122
2020-01-31 08:29:34.400792: I tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
2020-01-31 08:29:34.421951: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-31 08:29:34.482102: I tensorflow/cc/saved_model/loader.cc:202] Restoring SavedModel bundle.
2020-01-31 08:29:34.657523: I tensorflow/cc/saved_model/loader.cc:151] Running initialization op on SavedModel bundle at path: model/123123122
2020-01-31 08:29:34.764345: I tensorflow/cc/saved_model/loader.cc:311] SavedModel load for tags { serve }; Status: success. Took 384430 microseconds.
panic: op prob_out:0 not found
```

code:
```
        fakeInput0, _ := tf.NewTensor([1]float32{})
        fakeInput1, _ := tf.NewTensor([1]float32{})
        fakeInput2, _ := tf.NewTensor([1]float32{})
        fakeInput3, _ := tf.NewTensor([1]float32{})
        fakeInput4, _ := tf.NewTensor([1]float32{})
        fakeInput5, _ := tf.NewTensor([1]float32{})
        fakeInput6, _ := tf.NewTensor([1]float32{})
        fakeInput7, _ := tf.NewTensor([1]float32{})
        fakeInput8, _ := tf.NewTensor([1]float32{})
        fakeInput9, _ := tf.NewTensor([1]float32{})
        fakeInput10, _ := tf.NewTensor([1]float32{})
        fakeInput11, _ := tf.NewTensor([1]float32{})
        fakeInput12, _ := tf.NewTensor([1]float32{})
        fakeInput13, _ := tf.NewTensor([1]float32{})
        fakeInput14, _ := tf.NewTensor([1]float32{})
        fakeInput15, _ := tf.NewTensor([1]float32{})
        fakeInput16, _ := tf.NewTensor([1]float32{})
        fakeInput17, _ := tf.NewTensor([1]float32{})
        fakeInput18, _ := tf.NewTensor([1]float32{})
        fakeInput19, _ := tf.NewTensor([1]float32{})
        fakeInput20, _ := tf.NewTensor([1]float32{})

        results := model.Exec([]tf.Output{
                model.Op("prob_out:0", 0),
                model.Op("mul:0", 1),
                model.Op("calibration/add:0", 2),
                model.Op("stack:0", 3),
                model.Op("mul_1:0", 4),
                model.Op("mul_2:0", 5),
                model.Op("Sigmoid_1:0", 6),
                model.Op("Sigmoid:0", 7),
        }, map[tf.Output]*tf.Tensor{
                model.Op("Placeholder_17:0", 0): fakeInput0,
                model.Op("Placeholder_1:0", 1): fakeInput1,
                model.Op("Placeholder_19:0", 2): fakeInput2,
                model.Op("Placeholder_9:0", 3): fakeInput3,
                model.Op("Placeholder_9:0", 4): fakeInput4,
                model.Op("Placeholder:0", 5): fakeInput5,
                model.Op("Placeholder:16", 6): fakeInput6,
                model.Op("Placeholder:5", 7): fakeInput7,
                model.Op("Placeholder:13", 8): fakeInput8,
                model.Op("Placeholder:14", 9): fakeInput9,
                model.Op("Placeholder:7", 10): fakeInput10,
                model.Op("Placeholder:12", 11): fakeInput11,
                model.Op("Placeholder:2", 12): fakeInput12,
                model.Op("Placeholder:4", 13): fakeInput13,
                model.Op("Placeholder:11", 14): fakeInput14,
                model.Op("Placeholder:18", 15): fakeInput15,
                model.Op("Placeholder:10", 16): fakeInput16,
                model.Op("Placeholder:6", 17): fakeInput17,
                model.Op("Placeholder:8", 18): fakeInput18,
                model.Op("Placeholder:15", 19): fakeInput19,
                model.Op("Placeholder:3", 20): fakeInput20,
        })

        predictions := results[0].Value().([][]float32)
        fmt.Println(predictions)
```

**Comment by galeone** [comment]
You're almost there!
As you can see, the inputs and the outputs are in the format `name:number` (e.g. `prob_out:0`), where `name` is the name of the operation that generated the tensor, and `number` is the number of the output (0, is the first (and usually the only) output of the operation, 1 is the second (if any), and so on).

The tfgo `model.Op` method, wants you to define the input/output tensor in this way.
Thus, instead of `model.Op("prob_out:0", 0)` you have to write `model.Op("prob_out", 0)`, and so on, for every input/output tensor.
After that, it will work :)

**Comment by Arnold1** [comment]
@galeone ok :)

can you show me how to define these 2 inputs? first one is int64 second one is string. how to give the tensors input data? the following only defines there shape?
```
fakeInput0, _ := tf.NewTensor([1]int64{})
fakeInput1, _ := tf.NewTensor([1]string{})
```

also what about results?
```
predictions := results[0].Value().([][]float32)
```

I don't know where this is from:
```
panic: Expects arg[0] to be int64 but float is provided
```

**Comment by galeone** [comment]
It is slow because on the first run you create the `tf.Session`, you put the `tf.Graph` inside it and you execute the prediction.
Any other call should be faster because the session object has already been created and the graph loaded in memory

**Comment by Arnold1** [comment]
@galeone is there a way you can implement LoadModel to return an error and not throw a panic?

**Comment by galeone** [comment]
I don't think returning an error is the correct behavior. If you fail to load the model, then your application (that is based on that model) won't run, so IMO it is better to panic.
For the log string, it is generated from the TensorFlow C API, so I don't have control over it. But I guess if you wrap the model loading in a separate goroutine and you capture stderr and stdout,then you'll be able to suppress it

**Comment by Arnold1** [comment]
@galeone what I mean is the model cannot be loaded - but I want to give the user the error message so he understands why the model cannot be loaded and can take actions... do you know what I mean?

**Comment by arnwas** [comment]
Hi thanks. In #2 there seems a link to lead to your work, but it gives 404. Where is that "tree/rtf" now? Cheers, Arno

**Comment by galeone** [comment]
Currently, this has been moved to a separate repo, that is not working (it's a long and complex project and I don't have a lot of time to work on it): https://github.com/galeone/rtf

**Comment by Arnold1** [comment]
@galeone what is the difference between your lib and the go bindings here? https://www.tensorflow.org/install/lang_go

Also what tensorflow versions does your lib support? Is it suggested to use tf 2.1.x?

**Comment by galeone** [comment]
This library wraps the official Go bindings and adds some additional functionality. However, we are going out of topic, I'm closing this issue.

**Comment by Arnold1** [comment]
@galeone ok. Also what tensorflow versions does your lib currently support? Is it suggested to use tf 2.1.x?

**Comment by galeone** [comment]
The latest supported version is tensorflow 1.15, but only because I haven't tested it with other C libraries (there isn't still a C library of tensorflow 2.x).

However, if you use this library only to load SavedModels, you can export them using tensorflow 2.x (I've tested with 2.0) in Python and load them here (using the C library of Tensorflow 1.15), it works.
