### ISSUE TITLE
Possible to load model from memory?

### ISSUE THREAD

**Issue by lotsofone** [galeone/tfgo#44]
tfgo.LoadModel() method require the path to the model file on disk.
Suppose I have a []byte that contain a model file content, just downloaded from internet. Is it possible to directly load model from this []byte?

**Comment by galeone** [comment]
`LoadModel` accepts a path because the SavedModel serialization serialize and stores the model as a folder.

The support for frozen models (e.g.models all in one, with variables + structures all of them converted to a single optimized .pb) has been deprecated in TensorFlow 2.0 and it is going to be removed soon - that's why I support only loading from disk.

But maybe I misunderstood your question: do you have a SavedModel loaded in `[]byte`? If yes, how did you loaded it?

If instead, as I thought, you have a `.pb` file read as a `[]byte` this is not supported with tfgo.

It was present, however, you can go back to a specific commit (06635831fc69e3c9f0ca52e2a5606f07987ad13c) and load your frozen model using this version of tfgo (you also need some old TensorFlow C runtime installed, like 1.x)

**Comment by jeremyevith** [comment]
Loading models from []byte have a few advantages:

1. Able to ship a single binary with Go's new embed feature
2. Being able to apply some kind of encryption/decryption of models in memory

Unfortunately, looks like the current solution of going back to older Tensorflow versions aren't really viable.

**Comment by galeone** [comment]
Unfortunately, the SavedModel serialization format is a folder - maybe some kind of abstraction can be designed, in order to have a byte array and let tfgo interpret this as a path (since tfgo just invokes the standard TensorFlow C API for loading saved models, and this API wants a location on the disk). But honestly, I don't know if this is feasible or how can this become complex to design and implement
