### ISSUE TITLE
Invalid argument: shape must be a vector of {int32,int64}, got shape []

### ISSUE THREAD

**Issue by xiajohnnyxia** [galeone/tfgo#5]
I try to use the interface of RandomUniform as follows:

```
func TestRandomUniform(t *testing.T) {
	root := op.NewScope()

	T := op.Placeholder(root.SubScope("input"), tf.Int64)

	seed := op.RandomUniformSeed(-1.0)
	seed2 := op.RandomUniformSeed2(1.0)
	product := op.RandomUniform(root,T,tf.Float,seed,seed2)


	graph, err := root.Finalize()
	if err != nil {
		panic(err.Error())
	}

	var sess *tf.Session
	sess, err = tf.NewSession(graph, &tf.SessionOptions{})
	if err != nil {
		panic(err.Error())
	}

	var A *tf.Tensor

	if A, err = tf.NewTensor(int64(1)); err != nil {
		panic(err.Error())
	}

	var results []*tf.Tensor
	if results, err = sess.Run(
		map[tf.Output]*tf.Tensor{
			T: A,
		},
		[]tf.Output{product}, nil); err != nil {
			panic(err.Error())
	}
	for _, result := range results {
		fmt.Println(result.Value().([]int64))
	}

}
```

```
Invalid argument: shape must be a vector of {int32,int64}, got shape []
panic: shape must be a vector of {int32,int64}, got shape []
	 [[Node: RandomUniform = RandomUniform[T=DT_INT64, _class=[], dtype=DT_FLOAT, seed=-1, seed2=1, _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_input/Placeholder_0_0)]] [recovered]
	panic: shape must be a vector of {int32,int64}, got shape []
	 [[Node: RandomUniform = RandomUniform[T=DT_INT64, _class=[], dtype=DT_FLOAT, seed=-1, seed2=1, _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_input/Placeholder_0_0)]]

goroutine 5 [running]
```

But it  prints the error for me. What's it means?I am not good at c++.
And i try to use your tfgo.I get the same result.

**Comment by galeone** [comment]
Hey @xiajohnnyxia I just replyed to your email.

However, I'm gonna copy my reply here in order to help you and anyone else that'll face your same problem.

Now, you can easily find out that your problem is in the invocation of op.RandomUniform.

Let's look at the godoc: https://godoc.org/github.com/tensorflow/tensorflow/tensorflow/go/op#RandomUniform

Here's the signature:

func RandomUniform(scope *Scope, shape tf.Output, dtype tf.DataType, optional ...RandomUniformAttr) (output tf.Output)

Here's your invocation:
	output := op.RandomUniform(root,T,tf.Float,seed,seed2)
The first parameter is `scope *Scope` : you're passing `root` that's a `*Scope` -> perfect.
The second parameter is `shape tf.Output`: the tf.Output is a terrible type. It means "anything". The compiler can't help you raising an error and it will accept any parameter of tf.Output type.
The check if the right parameter is executed during runtime into the tensorflow environment.

We have to read the documentation: shape: The shape of the output tensor.

That's not really helpful if you are not familiar with tensorflow. But instead, if you are familiar with it, you know that the shape (even when using tensorflow in python) is *always* a list or tuple.

This means, in the context of tensorflow + go, that the shape parameter must be a vector of int32 or int64. (remember that a scalar value is a tensor with shape = () [ in python] that means a shape of []int32{} in go).

You're passing `T` as a `shape`. Your `T`parameter is a placeholder. A *scalar* placeholder, NOT a vector.

Thus you first have to change the definition of T, making it a vector of integers (with shape 0 -> that means empty tuple in python () -> that means the shape of a scalr value).

T := op.Placeholder(root.SubScope("input"), tf.Int32, op.PlaceholderShape(tf.MakeShape(0)))

Now you should be fine. First error fixed.


Let's go on comparing the signature and your function call:

The third parameter is: `dtype tf.DataType`: you're passing `tf.Float` that's a `tf.DataType` -> perect.
The 4th, 5h, ... parameters are `optional ...RandomUniforAttr`: you're passing `seed` and `seed2` that are `RandomUniforAttr`: -> perfect.

There's another problem in your code, in the Go side: when you execute the graph `sess.run(...)` you are fetching the value of `output` that's a `tf.float32` value.

This means that your cast `result.Value().([]int32)` will fail.

Instead, you have to cast the resulting interface to `[]float32`.


## Complete code

```go
package testTensorflow

import (
	"fmt"
	tf "github.com/tensorflow/tensorflow/tensorflow/go"
	"github.com/tensorflow/tensorflow/tensorflow/go/op"
	"testing"
)

func TestRandomUniform(t *testing.T) {
	root := op.NewScope()
	T := op.Placeholder(root.SubScope("input"), tf.Int32, op.PlaceholderShape(tf.MakeShape(0)))
	seed := op.RandomUniformSeed(-1.0)
	seed2 := op.RandomUniformSeed2(1.0)
	output := op.RandomUniform(root, T, tf.Float, seed, seed2)

	graph, err := root.Finalize()
	if err != nil {
		panic(err.Error())
	}

	var sess *tf.Session
	sess, err = tf.NewSession(graph, &tf.SessionOptions{})
	if err != nil {
		panic(err.Error())
	}

	var A *tf.Tensor
	if A, err = tf.NewTensor([]int32{1}); err != nil {
		panic(err.Error())
	}

	var results []*tf.Tensor
	if results, err = sess.Run(
		map[tf.Output]*tf.Tensor{
			T: A,
		},
		[]tf.Output{output}, nil); err != nil {
		panic(err.Error())
	}
	for _, result := range results {
		fmt.Println(result.Value().([]float32))
	}

}
```

Any question?

**Comment by galeone** [comment]
However, seriously, try to use `tfgo` as much as possible instead of using only the `op` package.
I know that's not the case where `tfgo` could help, but whatever. Also, when you'll become an expert, I'd love to have someone that contribute actively to tfgo

**Comment by xiajohnnyxia** [comment]
Thank you for your reply.It is work for me.Is `tf.MakeShape` 's param's value doesn't matter?

**Comment by galeone** [comment]
Yes, `tf.MakeShape` is useless when you define a placeholder because the placeholder is overwritten at runtime, thus its shape will be overwritten as well.

In fact you could change your placeholder definiition with:

    T := op.Placeholder(root.SubScope("input"), tf.Int32)

and the code will work without any problem.
In the context of placeholder what it matters is the shape of the tensor you feed.

**Comment by xiajohnnyxia** [comment]
thanks for your help.

**Comment by galeone** [comment]
You're welcome!
